version: "3"
services:
  openrpa-server:
    image: "openrpa-server"
    depends_on:
      - "openrpa-mongo"
    build: .
    ports:
      - "${PORT}:80"
    networks:
      - "backend"
  openrpa-mongo:
    container_name: "openrpa-mongo"
    image: "mongo:3.6"
    volumes:
      - "/var/lib/OpenRPA/mongo:/data/db"
    networks:
      - "backend"
networks:
  backend:
